return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      ---@diagnostic disable-next-line: missing-fields
      require("nvim-treesitter.configs").setup {
        ensure_installed = {
          "bash",
          "c",
          "cpp",
          "cmake",
          "css",
          "csv",
          "dockerfile",
          "gitignore",
          "go",
          "gomod",
          "gowork",
          "gosum",
          "hcl",
          "html",
          "javascript",
          "jq",
          "json",
          "lua",
          "luadoc",
          "make",
          "markdown",
          "markdown_inline",
          "python",
          "regex",
          "ron",
          "rust",
          "sql",
          "scss",
          "templ",
          "terraform",
          "tmux",
          "typescript",
          "vim",
          "vimdoc",
          "xml",
          "yaml",
        },
        -- Autoinstall languages that are not installed
        auto_install = true,
        highlight = { enable = true },
        indent = { enable = true },
      }
    end,
  },
}
